# -*- coding: utf-8 -*-
"""Project 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hTjneeEAaoS5stzastUpe4pzWi6iVX68
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')

from google.colab import files

uploaded = files.upload('Sales.csv')

df = pd.read_csv('Sales.csv/Sales.csv')
df.head()

df.info()

print("Rows and Columns:", df.shape)

df.isnull().sum()

(df.isnull().sum()/len(df))*100

df = df.dropna()

df.isnull().sum()

(df.isnull().sum()/len(df))*100

total_revenue = df['Amount'].sum()

print("Total Revenue:", total_revenue)

category_sales = df.groupby('Category')['Amount'].sum().sort_values(ascending=False)

category_sales

plt.figure(figsize=(10,5))

category_sales.plot(kind='bar')

plt.title('Revenue by Category')
plt.xlabel('Category')
plt.ylabel('Revenue')

plt.show()

state_sales = df.groupby('ship-state')['Amount'].sum().sort_values(ascending=False)

state_sales.head(10)

plt.figure(figsize=(12,6))

state_sales.head(10).plot(kind='bar')

plt.title('Top 10 States by Revenue')
plt.xlabel('State')
plt.ylabel('Revenue')

plt.show()

df['Status'].value_counts()
plt.figure(figsize=(10,6))

sns.countplot(data=df, y='Status')

plt.title('Order Status Distribution')

plt.show()

cancelled = len(df[df['Status'] == 'Cancelled'])

total_orders = len(df)

cancel_percentage = (cancelled / total_orders) * 100

print("Cancellation Percentage:", round(cancel_percentage,2), "%")

df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

monthly_sales = df.groupby(df['Date'].dt.month)['Amount'].sum()

monthly_sales

plt.figure(figsize=(10,5))

monthly_sales.plot(marker='o')

plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Revenue')

plt.show()

print("""
Business Recommendations

1. Increase inventory for Set category.
2. Promote Western Dress through discounts.
3. Reduce cancellation rates.
4. Improve delivery network in low-performing states.
5. Focus marketing campaigns on high-demand products.
""")